/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as AuthPoliciesRouteImport } from './routes/_auth/policies'
import { Route as AuthLeadsRouteImport } from './routes/_auth/leads'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthClientsRouteImport } from './routes/_auth/clients'
import { Route as AuthPoliciesIdRouteImport } from './routes/_auth/policies.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const AuthPoliciesRoute = AuthPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLeadsRoute = AuthLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientsRoute = AuthClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPoliciesIdRoute = AuthPoliciesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthPoliciesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof AuthClientsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/leads': typeof AuthLeadsRoute
  '/policies': typeof AuthPoliciesRouteWithChildren
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/policies/$id': typeof AuthPoliciesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof AuthClientsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/leads': typeof AuthLeadsRoute
  '/policies': typeof AuthPoliciesRouteWithChildren
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/policies/$id': typeof AuthPoliciesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/clients': typeof AuthClientsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/leads': typeof AuthLeadsRoute
  '/_auth/policies': typeof AuthPoliciesRouteWithChildren
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_auth/policies/$id': typeof AuthPoliciesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/leads'
    | '/policies'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/policies/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/leads'
    | '/policies'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/policies/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_public'
    | '/_auth/clients'
    | '/_auth/dashboard'
    | '/_auth/leads'
    | '/_auth/policies'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/register'
    | '/_auth/policies/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/policies': {
      id: '/_auth/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthPoliciesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/leads': {
      id: '/_auth/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthLeadsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clients': {
      id: '/_auth/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthClientsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/policies/$id': {
      id: '/_auth/policies/$id'
      path: '/$id'
      fullPath: '/policies/$id'
      preLoaderRoute: typeof AuthPoliciesIdRouteImport
      parentRoute: typeof AuthPoliciesRoute
    }
  }
}

interface AuthPoliciesRouteChildren {
  AuthPoliciesIdRoute: typeof AuthPoliciesIdRoute
}

const AuthPoliciesRouteChildren: AuthPoliciesRouteChildren = {
  AuthPoliciesIdRoute: AuthPoliciesIdRoute,
}

const AuthPoliciesRouteWithChildren = AuthPoliciesRoute._addFileChildren(
  AuthPoliciesRouteChildren,
)

interface AuthRouteChildren {
  AuthClientsRoute: typeof AuthClientsRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthLeadsRoute: typeof AuthLeadsRoute
  AuthPoliciesRoute: typeof AuthPoliciesRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthClientsRoute: AuthClientsRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthLeadsRoute: AuthLeadsRoute,
  AuthPoliciesRoute: AuthPoliciesRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
